server:
  port: 8081
spring:
  application:
    name: OurBlog
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://129.150.63.35:3306/db_OurBlog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: db_ourblog
      password: 123456
  servlet:
    multipart:
      # 上传图片限定大小为 1M
      max-file-size: 1MB

es.host: "168.138.174.87"
es.port: 9200

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 雪花算法
      id-type: ASSIGN_ID

upload:
  filePath: /home/www/OurBlog/imgs/
